name: pubviz
version: 2.3.9-dev
author: Kevin Moore <kevmoo@google.com>
description: Visualize package dependencies in your Dart project
homepage: https://github.com/kevmoo/pubviz
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  args: '>=0.13.0 <2.0.0'
  collection: ^1.0.0
  http: ^0.11.1+3
  path: ^1.0.0
  pub_semver: ^1.0.0
  stack_trace: ^1.6.0
  yaml: ^2.0.0
dev_dependencies:
  browser: any
  js: ^0.6.0-beta.5
  test: ^0.12.0
executables:
  pubviz: null
transformers:
- $dart2js:
    commandLineOptions:
      - --no-frequency-based-minification
      - --trust-type-annotations
      - --trust-primitives
      - --dump-info
