name: pubviz
version: 3.0.1-wip
description: >-
  A tool to visualize package dependencies and version constraints in your Dart
  project.
homepage: https://github.com/kevmoo/pubviz

environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.0.0
  build_cli_annotations: ^2.1.0
  collection: ^1.17.0
  gviz: ^0.4.0
  http: ^1.0.0
  io: ^1.0.0
  path: ^1.8.0
  pub_semver: ^2.0.0
  pubspec_parse: ^1.0.0
  stack_trace: ^1.10.0
  string_scanner: ^1.1.0
  yaml: ^3.1.0

dev_dependencies:
  build_cli: ^2.2.1
  build_runner: ^2.4.8
  build_verify: ^3.0.0
  build_version: ^2.0.3
  build_web_compilers: ^4.0.9
  dart_flutter_team_lints: ^3.0.0
  test: ^1.25.1
  test_descriptor: ^2.0.0
  test_process: ^2.0.0
  web: ^1.0.0

executables:
  pubviz: null
