name: pubviz
version: 3.0.1-dev
description: >-
  A tool to visualize package dependencies and version constraints in your Dart
  project.
homepage: https://github.com/kevmoo/pubviz

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  args: ^2.0.0
  build_cli_annotations: ^2.0.0
  collection: ^1.0.0
  gviz: ^0.4.0
  http: ^0.13.0
  io: ^1.0.0
  path: ^1.0.0
  pub_semver: ^2.0.0
  pubspec_parse: ^1.0.0
  stack_trace: ^1.6.0
  string_scanner: ^1.0.0
  yaml: ^3.0.0

dev_dependencies:
  build_cli: ^2.0.1
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  build_web_compilers: ^3.0.0
  js: ^0.6.1
  lints: ^2.0.0
  test: ^1.0.0
  test_descriptor: ^2.0.0
  test_process: ^2.0.0

executables:
  pubviz: null
